-- AlterTable
ALTER TABLE "Player" ALTER COLUMN "team" DROP NOT NULL,
ALTER COLUMN "rank" DROP NOT NULL,
ALTER COLUMN "positionalRank" DROP NOT NULL,
ALTER COLUMN "adp" DROP NOT NULL,
ALTER COLUMN "vorp" DROP NOT NULL,
ALTER COLUMN "projectedPoints" DROP NOT NULL,
ALTER COLUMN "lastSeasonPoints" DROP NOT NULL,
ALTER COLUMN "byeWeek" DROP NOT NULL,
ALTER COLUMN "userNotes" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "customTags" SET DEFAULT ARRAY[]::TEXT[];
